### ISSUE TITLE
建议给出科大邮箱的配置样例

### ISSUE THREAD

**Issue by ertuil** [zzh1996/ustc-grade-automatic-notification#14]
使用科大邮箱或者qq邮箱的人应当比较多吧，方便大家查smtp服务器地址了！

**Comment by zzh1996** [comment]
https://mail.ustc.edu.cn/coremail/help/index_zh_CN.jsp

**Comment by ertuil** [comment]
只是觉得可以尽量方便想使用（怕是dalao）的人啦。不过github上找到这里的人应该都会配邮箱吧....emmm
