### ISSUE TITLE
存在内存泄露问题

### ISSUE THREAD

**Issue by ziyixi** [zzh1996/ustc-grade-automatic-notification#5]
首先感谢zzh大神的脚本，我在我的vps上布置了一个，经确认存在内存泄露，一天大概有500m的样子(我的查询间隔是2min)。

**Comment by zzh1996** [comment]
这个脚本我在我内存1G的VPS上跑一假期并没有发现内存泄漏，间隔是5秒钟。而且python是有垃圾回收机制的。。。

**Comment by zzh1996** [comment]
也可以选择使用我写的 https://github.com/zzh1996/subscribe_to_anything 这个项目来监视成绩，我自己用这个系统监视数十个网页，已经运行半年多了

**Comment by ziyixi** [comment]
thanks a lot
